spring:
  application:
    name: ribbon-test
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://dcop:123456@peer1:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true