spring:
  application:
    name: eureka-client
  profiles:
    active: client2
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    datasource:                           # 指定数据源
      platform: h2                        # 指定数据源类型
      schema: classpath:schema.sql        # 指定h2数据库的建表脚本
      data: classpath:data.sql            # 指定h2数据库的数据脚本
logging: # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://dcop:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true


---
server:
  port: 8080
spring:
  profiles: client1
---
server:
  port: 8081
spring:
  profiles: client2