spring:
  application:
    name: eureka-server-high-avaliablity
#  profiles:
#    active: pee
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka
    register-with-eureka: false
security:
  user:
    name: dcop
    password: 123456
  basic:
    enabled: true
#spring:
#  profiles: peer1
#---
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    service-url:
#      defaultZone: http://user:1234@peer1:8761/eureka/
#spring:
#  profiles: peer2